apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 825522381980-t3p3qp1g4lasi0p2ctpqv0lllfa0nm8s.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://34.9.95.190.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
