apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLUpFdnhpY0VPV1o0T3UwNmtwUE45NFdCR0JZeTA= # Base64 for google key
  NEXTAUTH_SECRET: jfxuwmSXn6XmUkGH2lS9MHrQ+rnQWo08DfhfGL8e7bw= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5RGxOSXBhR2NCc2VFZDZCQloxRlhrakxKYkJ4SEUxcWVR # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
